## Análisis de datos - Clase 1

#### Actividad: primera inspección del dataset y sus variables

Importar y hacer una exploración inicial del dataset datasets/datos.csv para responer las preguntas que se encuentran a continuación.
Tip: pueden ser útiles los métodos `head()/tail()`, `info()`, `unique()`,`nunique()`, `value_counts()` y las propiedades `shape` y `columns` de pandas.

**Identificar esta información:**

1. Número de filas y columnas: (891, 15)
2. Nombres de las columnas: 

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
 'embarked', 'class', 'who', 'adult_male', 'deck',
 'embark_town', 'alive', 'alone']

3. Variables numéricas (y subtipo): 

- survived (int64)
- pclass (int64)
- age (float64)
- sibsp (int64)
- parch (int64)
- fare (float64)

4. Variables categóricas (y subtipo): 

- sex (str)
- embarked (str)
- class (str)
- who (str)
- adult_male (bool)
- deck (str)
- embark_town (str)
- alive (str)
- alone (bool)

5. ¿Tiene datos faltantes el dataset?

Valores faltantes por variable

- survived: 0
- pclass: 0
- sex: 0
- age: 177
- sibsp: 0
- parch: 0
- fare: 0
- embarked: 2
- class: 0
- who: 0
- adult_male: 0
- deck: 688
- embark_town: 2
- alive: 0
- alone: 0


In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
# Importar datasets/datos.csv en un df de Pandas  

df = pd.read_csv("../datasets/titanic.csv")

In [32]:
# Visualizar las primeras filas del dataset
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [33]:
# Visualizar las últimas filas del dataset
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [6]:
# Número de filas y columnas del dataset
df.shape

(891, 15)

In [7]:
# Nombres de las columnas del dataset
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [10]:
# Información general del dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    str    
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str    
 8   class        891 non-null    str    
 9   who          891 non-null    str    
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    str    
 12  embark_town  889 non-null    str    
 13  alive        891 non-null    str    
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB


In [11]:
# Explorar las variables (por ejemplo los valores únicos)
for col in df.columns:
    print(f"\nColumna: {col}")
    print(df[col].unique())


Columna: survived
[0 1]

Columna: pclass
[3 1 2]

Columna: sex
<StringArray>
['male', 'female']
Length: 2, dtype: str

Columna: age
[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]

Columna: sibsp
[1 0 3 4 2 5 8]

Columna: parch
[0 1 2 5 3 4 6]

Columna: fare
[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55    31.275    7.8542  16.      29.125
  13.      18.       7.225   26.       8.0292  35.5     31.3875 263.
   7.8792   7.8958  27.7208 146.5208   7.75   

In [27]:
# Frecuencia de cada valor en cada columna
for col in df.columns:
    print(df[col].value_counts())

survived
0    549
1    342
Name: count, dtype: int64
pclass
3    491
1    216
2    184
Name: count, dtype: int64
sex
male      577
female    314
Name: count, dtype: int64
age
24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64
sibsp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64
parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64
fare
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
13.8583     1
50.4958     1
5.0000      1
9.8458      1
10.5167     1
Name: count, Length: 248, dtype: int64
embarked
S    644
C    168
Q     77
Name: count, dtype: int64
class
Third     491
First     216
Second    184
Name: count, dtype: int64
who
man      537
woman    271
child     83
Name: count, dtype: int64
adult_male
True     537
False    354
Name: count, dtype: int64

In [34]:
# Tipos de datos de cada columna
df.dtypes

survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

In [ ]:
# Resumen estadístico de las columnas numéricas
df.describe()

In [ ]:
# Cantidad de valores faltantes en cada columna
df.isna().sum()

In [29]:
# Cantidad de valores faltantes en cada columna 
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
# Visualizar la distribución de las variables numéricas
df.hist(figsize=(10,8))

In [ ]:
# Cantidad de valores duplicados en el dataset
df.duplicated().sum()

np.int64(107)

In [ ]:
# Visualizar las filas duplicadas
df[df.duplicated()]